# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLYYVt6ChMmY-gc202FfiWt5-n9vxYCm
"""
import gradio as gr
import os
import requests
import pdfplumber
from dotenv import load_dotenv

# Configuração da API
load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
API_URL = "https://openrouter.ai/api/v1/chat/completions"
HEADERS = {
    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
    "Content-Type": "application/json"
}
MODEL = "mistralai/mistral-7b-instruct"

# Modelo de currículo de referência
MODELO_DEMO = """
MARIA SILVA
(11) 98765-4321 | maria.silva@email.com | São Paulo/SP
LinkedIn: linkedin.com/in/mariasilva
OBJETIVO
Gerente de Logística
## RESUMO DE QUALIFICAÇÕES
- 8+ anos em gestão logística
- Especialista em SAP e Power BI
- Redução de custos logísticos em 30% na empresa anterior
- Certificação Lean Six Sigma
## EXPERIÊNCIA PROFISSIONAL
- Gerente de Logística - Empresa XYZ | 2020-Presente
- Gerenciou equipe de 15 pessoas, reduzindo atrasos em 25%
- Implementou novo sistema WMS, aumentando eficiência em 40%
- Negociou contratos com transportadoras, economizando R$ 1,2M/ano
### Analista Sênior - Empresa ABC | 2015-2020
- Automatizou relatórios, reduzindo tempo de análise em 70%
- Coordenou projeto de redistribuição de estoques
## FORMAÇÃO
- Administração - USP (2014)
- Pós-graduação em Supply Chain - FGV (2016)
## HABILIDADES
- SAP Logístico (Avançado)
- Power BI (Intermediário)
- Inglês Fluente
"""

# Extrai o texto do PDF
def extract_text(file):
    try:
        with pdfplumber.open(file.name) as pdf:
            return "\n".join([page.extract_text() for page in pdf.pages if page.extract_text()])
    except Exception as e:
        raise gr.Error(f"Erro ao ler o PDF: {str(e)}")

# Chama a API da IA com tratamento de erro
def call_llm(prompt, system_role):
    try:
        response = requests.post(API_URL, headers=HEADERS, json={
            "model": MODEL,
            "messages": [
                {"role": "system", "content": system_role},
                {"role": "user", "content": prompt}
            ]
        })

        if response.status_code != 200:
            return f"❌ Erro da API ({response.status_code}): {response.text}"

        data = response.json()

        if "choices" in data and data["choices"]:
            return data["choices"][0]["message"]["content"]
        else:
            return f"❌ Erro: resposta inesperada da API:\n{data}"

    except Exception as e:
        return f"❌ Erro na chamada da IA: {str(e)}"

# Prompt otimizado para análise ATS
def gerar_prompt_avaliacao(texto):
    return f"""
Você é um recrutador especialista em análise de currículos para sistemas de triagem automática (ATS), como Gupy, Kenoby e similares.
Recebeu o seguinte currículo:
--- INÍCIO DO CURRÍCULO ---
{texto}
--- FIM DO CURRÍCULO ---
Sua tarefa é gerar um relatório completo, claro e prático contendo:
1. ✅ Análise ATS Detalhada
   - O currículo está bem formatado para leitura automática?
   - As palavras-chave mais importantes para a área estão presentes?
   - Há seções obrigatórias faltando (Resumo, Experiência, Habilidades, etc)?
   - Existem erros ou excessos que podem prejudicar a triagem?
2. 📊 Pontuação (0-100)
   - Adaptação para ATS: XX/100
   - Clareza e Leitura por Humanos: XX/100
3. 📌 Recomendações Práticas
   - O que falta para aumentar as chances de passar em sistemas ATS?
   - Que palavras-chave, competências ou métricas poderiam ser adicionadas?
   - Sugira também melhorias específicas por seção (Resumo, Experiência, etc.)
4. 💡 Resumo Final em Tópicos
   - Pontos fortes
   - Pontos de atenção
   - Ações imediatas para melhorar o currículo
"""

# Função para analisar currículo
def analisar_curriculo(file):
    texto = extract_text(file)
    prompt = gerar_prompt_avaliacao(texto)
    resultado = call_llm(prompt, "Você é um especialista em recrutamento técnico.")
    caminho = salvar_txt(resultado, "analise_curriculo.txt")
    return resultado, caminho

# Função para melhorar currículo
def melhorar_curriculo(file):
    texto = extract_text(file)
    prompt = f"""
Melhore este currículo com base no seguinte modelo:
{MODELO_DEMO}
Texto original:
{texto}
Regras:
1. Mantenha todas as informações
2. Use a estrutura do modelo
3. Adicione métricas sempre que possível
4. Responda em formato markdown
"""
    resultado = call_llm(prompt, "Você é um revisor de currículos profissional.")
    caminho = salvar_txt(resultado, "curriculo_otimizado.txt")
    return resultado, caminho

# Salva saída como arquivo
def salvar_txt(conteudo, nome_arquivo):
    caminho = f"/tmp/{nome_arquivo}"
    with open(caminho, "w", encoding="utf-8") as f:
        f.write(conteudo)
    return caminho

# Interface Gradio
with gr.Blocks(title="Otimizador de Currículo Pro") as app:
    gr.HTML("<h1 style='text-align: center; color: #1f77b4;'>Otimizador Profissional de Currículos</h1>")

    with gr.Tabs():
        with gr.Tab("Análise para Gupy"):
            file_input1 = gr.File(label="Envie seu currículo em PDF", file_types=[".pdf"])
            btn1 = gr.Button("Analisar Currículo")
            resultado1 = gr.Textbox(label="Resultado da Análise", lines=25)
            download1 = gr.File(label="Baixar Resultado")
            btn1.click(analisar_curriculo, inputs=[file_input1], outputs=[resultado1, download1])

        with gr.Tab("Melhorar Currículo"):
            file_input2 = gr.File(label="Envie seu currículo em PDF", file_types=[".pdf"])
            btn2 = gr.Button("Melhorar Currículo")
            resultado2 = gr.Textbox(label="Currículo Otimizado", lines=25)
            download2 = gr.File(label="Baixar Currículo")
            btn2.click(melhorar_curriculo, inputs=[file_input2], outputs=[resultado2, download2])

        with gr.Tab("Modelo Ideal"):
            modelo = gr.Textbox(value=MODELO_DEMO.strip(), label="Modelo Padrão de Currículo", lines=25, interactive=False)

if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=7860)

